default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_DEVELOPMENT") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_TEST") %>

production:
  <<: *default
  # database:
